### ISSUE TITLE
fix the enmy is nlt defined error with the boy controler 

### ISSUE THREAD

**Issue by Froggythedoctor** [kennyrkun/quantumjump#29]
When using gamer there is a Unity Exception \: tag: Enemy is not defined. heath.Update And is logged 33675 times

**Comment by kennyrkun** [comment]
Please provide a detailed error report so I can further investigate this issue.

**Comment by Froggythedoctor** [comment]
This happens when the play is active

**Comment by kennyrkun** [comment]
I think I know what causes this, however, I am unable to reproduce the issue on my own machine.

If you want, I can attempt to fix it on yours. However, I don't believe that's quire necessary since the project you're currently using is out of date, and will not be the project which is built for the release of the game.

**Comment by Ottersolutions** [comment]
did you have a stroke writing the error and the first comment
